#117/api endpoint de orcamento
aceleradora-TW/descarte-certo pull request #130
Opened 2021-05-20 18:37 UTC by JessicaFreua

- Adicionamos o retorno do calculo do orçamento de caçambas e sacos.

- Alteramos o método calculateBucketEstimate da classe BucketCalculator para public.

2021-05-20 18:59 UTC, GabrieRabelo reviewed
Deixei alguns comentários :P

2021-05-20 18:59 UTC, GabrieRabelo commented on backend/src/main/java/com/thoughtworks/aceleradora/controller/QuickEstimatesController.java
> +@RequestMapping(path = "/estimates") //Acessa a classe
Precisamos manter esses comentários? (O mesmo comentário para a linha 24)

2021-05-20 18:59 UTC, GabrieRabelo commented on backend/src/main/java/com/thoughtworks/aceleradora/controller/QuickEstimatesController.java
> +        QuickEstimateCalculator calculator = new QuickEstimateCalculator();
Acredito que seja melhor criar um atributo quickEstimateCalculator e utilizar injeção de dependencia nesse carinha aqui, já utilizaram algo do tipo?

2021-05-20 18:59 UTC, GabrieRabelo commented on backend/src/main/java/com/thoughtworks/aceleradora/service/BucketCalculator/BucketCalculator.java
>          if (params.getBucketZones() == DONWTOWN || params.getBucketZones() == SOUTHZONE || params.getMaterials() == MIXED) {
Sei que não é deste PR, mas DONWTOWN deveria ser DOWNTOWN (n e w trocam as posições)

2021-05-20 18:59 UTC, GabrieRabelo commented on backend/src/main/java/com/thoughtworks/aceleradora/controller/QuickEstimatesController.java
> +    public BigDecimal returnEstimateBucket(@PathVariable("quantidadeCacambas") int quantidadeCacambas, @PathVariable("zonas")BucketZones zonas, @PathVariable("materiais") Materials materiais){
Aqui o parâmetro zonas deveria ser zona, tendo em vista que é um enum, e só pode escolher um :P
Acho que o mesmo pode servir para o parâmetro materiais.

2021-05-20 18:59 UTC, GabrieRabelo commented on backend/src/main/java/com/thoughtworks/aceleradora/controller/QuickEstimatesController.java
> +    public BigDecimal returnEstimateBag(@PathVariable("quantidadeSacos") int quantidadeSacos, @PathVariable("acesso") FloorAccess acesso,@PathVariable("materiais") Material materiais){
Atributo materiais, mesmo comentário do endpoint abaixo.

2021-05-20 19:12 UTC, yrachid requested changes

2021-05-20 19:22 UTC, yrachid commented on backend/src/main/java/com/thoughtworks/aceleradora/controller/QuickEstimatesController.java
> +    public BigDecimal returnEstimateBucket(@PathVariable("quantidadeCacambas") int quantidadeCacambas, @PathVariable("zonas")BucketZones zonas, @PathVariable("materiais") Materials materiais){
Aproveitando o gancho do @GabrieRabelo, parece que o mesmo conceito de material é representado por dois enums diferentes:
- Representado por [com.thoughtworks.aceleradora.service.quickestimates.Material](https://github.com/aceleradora-TW/descarte-certo/blob/master/backend/src/main/java/com/thoughtworks/aceleradora/service/quickestimates/Material.java)
- Representado por [com.thoughtworks.aceleradora.service.BucketCalculator.Materials](https://github.com/aceleradora-TW/descarte-certo/blob/master/backend/src/main/java/com/thoughtworks/aceleradora/service/BucketCalculator/Materials.java)

Eu recomendo fortemente seguir somente com um. É uma opinião mais pessoal, mas eu gosto de nomear enums no singular, mas isso depende do gosto do time.

2021-05-20 19:52 UTC, yrachid commented on backend/src/main/java/com/thoughtworks/aceleradora/controller/QuickEstimatesController.java
> +    @GetMapping(path = "/bucket/{quantidadeCacambas}/{zonas}/{materiais}")
Queria aproveitar a situação para trazer outro ponto de atenção, que é definir um tipo primitivo como parâmetro de requisição. Existem algumas situações em que o Spring não consegue converter valores primitivos, é o caso de parâmetros opcionais. Nestas situações, a solução é utilizar o tipo [encaixotado](https://stackoverflow.com/a/1418302) correspondente.

Vejam o seguinte cenário:

```java
@GetMapping("/primitivo")
public String primitivo(@RequestParam(required = false) int value) {
    return Integer.toString(value);
}

@GetMapping("/boxed")
public String boxed(@RequestParam(required = false) Integer value) {
    return value == null
            ? "No value specified"
            : Integer.toString(value);
}
```

No primeiro endpoint, a requisição vai falhar quando o valor não for passado, no segundo, o Spring irá definir o parâmetro como `null` (algo que não é possível com tipos primitivos) e o baile segue:

![Screenshot_20210520_164747](https://user-images.githubusercontent.com/4705127/119040304-a2ed8580-b98b-11eb-88df-13d1b9ac2847.png)

Não acho que seja necessariamente um problema na situação de vocês, dado que o parâmetro amount é obrigatório, mas tenham isso em mente para situações futuras. :)

2021-05-21 18:38 UTC, JessicaFreua commented
Alterações concluídas.

2021-05-25 19:28 UTC, yrachid commented on backend/src/main/java/com/thoughtworks/aceleradora/controller/QuickEstimatesController.java
> +            @RequestParam("materials") Materials materials){
Esse parâmetro ainda está no plural, mesmo sendo um único valor.

2021-05-25 19:29 UTC, yrachid commented on backend/src/main/java/com/thoughtworks/aceleradora/controller/QuickEstimatesController.java
> +            @RequestParam("materials") Materials materials){
Esse parâmetro ainda está no plural, mesmo sendo um único valor.

2021-05-25 19:31 UTC, yrachid approved these changes

2021-05-27 17:19 UTC, nicoledbianchin commented on backend/src/main/resources/application.yml
> +  username: ${MAILGUN_USERNAME:"user"}
isso não pode ir para a master, precisamos que no ambiente de HML e PRD ele pegue essas variáveis do ambiente

2021-05-27 17:29 UTC, nicoledbianchin approved these changes

2021-05-27 17:29 UTC, ghidorsi requested changes
To um pouco na dúvida pq não estamos usando `@Service` ou `@Component` e utilizando Injection Dependency nas controllers. Alguém sabe me dizer se a gente não viu isso ou o pq a gente não ta usando? (@yrachid @nicoledbianchin)

Outra coisa que notei é que temos alguns pacotes com camel case ao invés de `snake_case`, como no caso do pacote `BucketCalculator`.

2021-05-27 17:29 UTC, ghidorsi commented on backend/src/main/resources/application.yml
> +  username: ${MAILGUN_USERNAME:"user"}
Mas `MAILGUN_USERNAME` e `MAILGUN_PASSWORD` não são var envs nos servidores remotos?

2021-05-28 14:59 UTC, ghidorsi approved these changes

2021-05-28 15:07 UTC, yrachid commented on backend/src/main/resources/application.yml
> +  username: ${MAILGUN_USERNAME:"user"}
Idealmente, penso que estes fallbacks deveriam estar no profile de `dev`, assim, isso só funcionará nas máquinas locais e não corremos o risco de usar esses fallbacks em homologação em produção (caso as variáveis não estejam definidas, por algum motivo). Assim, resolvemos o problema de inicialização local sem interferir nos ambientes.

2021-05-28 17:15 UTC, merged