158/refatorar modal
aceleradora-TW/descarte-certo pull request #214
Opened 2021-07-08 18:50 UTC by liasantos

2021-07-08 19:30 UTC, nicoledbianchin approved these changes

2021-07-08 19:36 UTC, Queiroxzz approved these changes

2021-07-08 19:40 UTC, GabrieRabelo requested changes

2021-07-08 19:40 UTC, GabrieRabelo commented on frontend/src/components/Modal/ModalShowAndHide.js
> +/*const OrderForm = ({ display, onClick }) => {
isso fica aqui comentado? 🧐

2021-07-08 19:43 UTC, GabrieRabelo commented on frontend/src/components/Modal/ModalShowAndHide.js
> +    /*orderForm:  true,*/
e esse comentário? fica?

2021-07-08 21:07 UTC, narukaioh commented on frontend/src/components/Modal/ModalShowAndHide.js
> +/*const OrderForm = ({ display, onClick }) => {
É então, eles fizeram essa branch apartir de uma branch que esta bloqueda, e como a gente ta com um pouco de urgencia e teoricamente essa parte do codigo nao ta sendo usada eu pedi pra eles fazerem o commit mesmo assim

2021-07-08 21:09 UTC, narukaioh approved these changes

2021-07-08 21:10 UTC, GabrieRabelo commented on frontend/src/components/Modal/ModalShowAndHide.js
> +/*const OrderForm = ({ display, onClick }) => {
Me preocupa deixar coisas pra trás na urgencia, deixando coisas não utilizadas na master, mas tudo bem hehehe

2021-07-08 21:11 UTC, GabrieRabelo approved these changes

2021-07-09 11:41 UTC, narukaioh commented on frontend/src/components/Modal/ModalShowAndHide.js
> +/*const OrderForm = ({ display, onClick }) => {
Certíssimo!

2021-07-09 12:59 UTC, merged