220/envia informacoes calculo backend
aceleradora-TW/descarte-certo pull request #225
Opened 2021-07-13 17:36 UTC by Eduardo-LP

2021-07-13 18:18 UTC, EduardaSchuler approved these changes

2021-07-13 19:07 UTC, narukaioh requested changes

2021-07-13 19:07 UTC, narukaioh commented on frontend/src/components/Modal/OrderForm.js
> +        access: values.accessType
Colocar o adapter ein hehehe

2021-07-14 15:07 UTC, narukaioh approved these changes

2021-07-15 17:37 UTC, merged