#23/beneficios/ajustes
aceleradora-TW/descarte-certo pull request #43
Opened 2020-10-13 12:23 UTC by alinenecchi

@isadoramz @alinenecchi

2020-10-13 12:34 UTC, lucasbz requested changes

2020-10-13 12:34 UTC, lucasbz commented on frontend/src/components/NavBar/index.js
> +                    <Nav.Link className="nb" href="#Beneficios" >Benefícios</Nav.Link>
Oi, qual a motivação para colocar apenas esse link em português? Sugiro manter a consistência.. ou continua em inglês, ou os outros podem ser traduzidos, que acham?

2020-10-13 13:15 UTC, Queiroxzz approved these changes

2020-10-13 16:18 UTC, alinenecchi commented on frontend/src/components/NavBar/index.js
> +                    <Nav.Link className="nb" href="#Beneficios" >Benefícios</Nav.Link>
Sim , concordo , e esses já estão sendo ajustados em outro card. Na verdade foi precipitado da minha parte alterar o link de benefícios.

2020-10-13 18:10 UTC, Queiroxzz approved these changes

2020-10-13 18:10 UTC, Queiroxzz commented on frontend/src/components/Footer/index.js
> +            <div id ="Contato"className="footerStyle" fixed="bottom">
Acho que quando vcs foram mudar o nome do link, acabaram mudando esse id tb, ele é pra ser em português tb? Pq a maioria dos outros id no código estão em inglês

2020-10-13 20:06 UTC, lucasbz approved these changes

2020-10-13 20:07 UTC, lucasbz approved these changes

2020-10-13 20:07 UTC, lucasbz approved these changes

2020-10-14 12:15 UTC, rosafreire approved these changes

2020-10-14 12:15 UTC, merged