Correção de problemas do FAQ e navbar
aceleradora-TW/descarte-certo pull request #59
Opened 2020-10-29 18:42 UTC by jhuan0999

- Adicionada responsividade para mobile
- Alterado o nome de FAQ para duvidas
- Navbar duplicada tirada
- Alterada a imagem que fica embaixo do FAQ

2020-10-29 18:45 UTC, nicoledbianchin approved these changes

2020-10-29 18:51 UTC, Queiroxzz requested changes

2020-10-29 18:51 UTC, Queiroxzz commented on frontend/src/components/FAQ/FaqStyle.css
>  /* Alteracao do estilo do btn do bootstrap */
retirar comentário

2020-10-29 18:51 UTC, Queiroxzz commented on frontend/src/components/FAQ/FaqStyle.css
>  /* Alteracao da cor de fundo do FAQ */
comentario aqui tb

2020-10-29 18:51 UTC, Queiroxzz commented on frontend/src/components/FAQ/FaqStyle.css
> +    padding: 0px;
pq a gnt tem uma padding se ela é 0px?

2020-10-29 18:51 UTC, Queiroxzz commented on frontend/src/components/FAQ/FaqStyle.css
> +    border-radius: .0rem;
na vdd esse código ta repetido

2020-10-29 18:51 UTC, Queiroxzz commented on frontend/src/components/FAQ/FaqStyle.css
> +    padding-bottom: 0px;
Mesma coisa daquela que comentei lá em cima

2020-10-29 18:51 UTC, Queiroxzz commented on frontend/src/components/FAQ/FaqStyle.css
> +     right: 0px;
Podemos retirar isso tb

2020-10-29 18:51 UTC, Queiroxzz commented on frontend/src/components/FAQ/FaqStyle.css
> +      padding: 0px;
padding zerada aqui tb

2020-10-29 18:51 UTC, Queiroxzz commented on frontend/src/components/FAQ/FaqStyle.css
> +      padding-left: 0px;
aqui tb

2020-10-29 18:51 UTC, Queiroxzz commented on frontend/src/components/FAQ/FaqStyle.css
> +    padding-left: 0px;
aqui tb

2020-10-29 19:44 UTC, Queiroxzz approved these changes

2020-11-04 02:26 UTC, HodaraMachado commented on frontend/src/components/FAQ/FaqComponent.js
> +                            </Accordion.Collapse>   </Accordion.Toggle>
Quebrar a linha para a TAG </Accordion.Toggle> para o código ficar mais legível .

2020-11-04 02:35 UTC, HodaraMachado commented on frontend/src/components/FAQ/FaqStyle.css
> +  .jumbotron {
Pq está duplicado o estilo para a classe jumbotron? na linha 99 está igual.

2020-11-04 02:40 UTC, HodaraMachado commented on frontend/src/components/FAQ/FaqStyle.css
> +    .card.card {
Pq está duplicado o estilo para a classe .card.card? na linha 142 está igual.

2020-11-04 02:41 UTC, HodaraMachado commented on frontend/src/components/FAQ/FaqStyle.css
> +  .card-header {
.card-header está duplicada também, na linha 156

2020-11-04 02:43 UTC, HodaraMachado commented on frontend/src/components/FAQ/FaqStyle.css
> +    .card.card {
Duplicado de novo , faz sentido?

2020-11-04 02:43 UTC, HodaraMachado commented on frontend/src/components/FAQ/FaqStyle.css
> +  .card-header {
Duplicado de novo , faz sentido?

2020-11-04 02:44 UTC, HodaraMachado commented on frontend/src/components/FAQ/FaqStyle.css
> +  .jumbotron {
Duplicado de novo , faz sentido?

2020-11-05 19:21 UTC, lucasbz commented on frontend/debug.log
> +[1028/125927.963:ERROR:directory_reader_win.cc(43)] FindFirstFile: The system cannot find the path specified. (0x3)
Oi, podemos remover esse log do git? (Colocar no .gitgnore)
Esse tipo de arquivo normalmente não precisa ficar no git.

2020-11-06 19:26 UTC, merged