26/solicitacao orcamento base
aceleradora-TW/descarte-certo pull request #75
Opened 2020-11-24 17:49 UTC by rosafreire

Editamos os testes que faltavam ser atualizados

2020-11-24 17:52 UTC, nicoledbianchin commented on backend/src/main/java/com/thoughtworks/aceleradora/controller/EstimateController.java
> +        //FIXME remover apos backend estar pronto
acho mais interessante termos uma parede de débitos tecnicos do que os comentarios no código. talvez faça parte da documentação para possibilitar a continuação do projeto depois da aceleradora. o que voces acham?

2020-11-24 17:54 UTC, Queiroxzz approved these changes

2020-11-24 17:54 UTC, Queiroxzz commented on backend/src/main/java/com/thoughtworks/aceleradora/controller/EstimateController.java
> +        //FIXME remover apos backend estar pronto
a gnt pode tirar essesc comentários já

2020-11-24 17:54 UTC, Queiroxzz commented on backend/src/test/java/com/thoughtworks/aceleradora/service/EstimateConverterServiceTest.java
>          //DADO uma requisição de solicitacao de orcamento valida (Estimate)
comentários

2020-11-24 17:54 UTC, Queiroxzz commented on frontend/src/components/Modal/Modal.js
> +                                        submitSuccess ? "Sua solicitação foi enviada! Obrigado!" :
cometário

2020-11-24 17:54 UTC, Queiroxzz commented on frontend/src/constant.js
> +    /*if (!nameCompleted || !/^[A-Z]i.test(nameCompleted)){
Comentário

2020-11-24 17:55 UTC, nicoledbianchin requested changes

2020-11-24 17:55 UTC, nicoledbianchin commented on backend/src/main/java/com/thoughtworks/aceleradora/entity/Requester.java
> +    private String nameCompleted;
o certo é ```fullName``` ou ```completeName```

2020-11-24 17:55 UTC, nicoledbianchin commented on backend/src/main/resources/db/migration/V202010291545__dara_dine_duda_add_column_requester_table.sql
> +    ADD COLUMN nameCompleted VARCHAR(100),
mesma coisa aqui. precisamos de uma migration para alterar o nome da coluna

2020-11-24 17:55 UTC, nicoledbianchin commented on backend/src/test/resources/createSolicitacaoRequest.json
> +    "nameCompleted": "",
```fullName``` ou ```completeName```

2020-11-24 17:55 UTC, nicoledbianchin commented on backend/src/test/java/com/thoughtworks/aceleradora/service/ValidEstimateRequestFactory.java
> +                        .nameCompleted("Pedro")
```fullName``` ou ```completeName```

2020-11-24 17:55 UTC, nicoledbianchin commented on backend/src/test/java/com/thoughtworks/aceleradora/service/EstimateConverterServiceTest.java
> +        validEstimateRequest.getRequester().setNameCompleted(expectedRequesterName);
```setFullName``` ou ```setCompleteName```

2020-11-24 17:55 UTC, nicoledbianchin commented on backend/src/test/java/com/thoughtworks/aceleradora/service/CreateEstimateFunctionalTestTool.java
> +                                    .nameCompleted("Leo")
```fullName``` ou ```completeName```

2020-11-24 17:55 UTC, nicoledbianchin commented on backend/src/main/java/com/thoughtworks/aceleradora/service/EstimateConverterService.java
> +                                .nameCompleted(request.getRequester().getNameCompleted())
```fullName``` ou ```completeName```

2020-11-24 17:55 UTC, nicoledbianchin commented on frontend/src/components/Modal/Modal.js
> +           // console.log(JSON.stringify(values));
apagar comentários

2020-11-24 17:55 UTC, nicoledbianchin commented on frontend/src/constant.js
> +    /*if (!nameCompleted || !/^[A-Z]i.test(nameCompleted)){
apagar comentarios

2020-11-24 18:23 UTC, ldiasrs requested changes

2020-11-24 18:23 UTC, ldiasrs commented on backend/src/main/java/com/thoughtworks/aceleradora/controller/EstimateController.java
> +       return EstimateResponse.builder().build();
Aqui poderiamos passar de voltya o codigo do Estimate no banco não? timpo assim:
```suggestion
      Estimate estimateEntity = estimateService.create(estimateRequest);
       return EstimateResponse.builder()
               .estimateCode(estimateEntity.getId())
               .build();
       
```

2020-11-24 18:23 UTC, ldiasrs commented on backend/src/main/java/com/thoughtworks/aceleradora/entity/Requester.java
> +    private String nameCompleted;
Cuidar que quando mudar isso tem que refletir com uma mudança no bando de dados ;)

2020-11-24 18:23 UTC, ldiasrs commented on backend/src/test/java/com/thoughtworks/aceleradora/service/EstimateConverterServiceTest.java
>          //DADO uma requisição de solicitacao de orcamento valida (Estimate)
Ao meu ver, é um comentário de BDD ilustrativo para aprendizado não vejo tanto problem nesse caso.

2020-11-25 18:05 UTC, nicoledbianchin approved these changes

2020-11-25 18:36 UTC, rosafreire commented on backend/src/main/java/com/thoughtworks/aceleradora/controller/EstimateController.java
> +       return EstimateResponse.builder().build();
Resolvido @ldiasrs ^^

2020-11-26 13:54 UTC, ldiasrs approved these changes

2020-11-26 13:54 UTC, merged