28/orcamento info residuo
aceleradora-TW/descarte-certo pull request #81
Opened 2020-12-01 17:27 UTC by vanderleijrs

2020-12-01 17:31 UTC, nicoledbianchin approved these changes

2020-12-01 17:42 UTC, GabrieRabelo requested changes

2020-12-01 17:42 UTC, GabrieRabelo commented on backend/src/main/java/com/thoughtworks/aceleradora/controller/request/ResidueRequest.java
> +    private String residueMensure;
Não deveria ser residueMeasure?

2020-12-01 17:42 UTC, GabrieRabelo commented on backend/src/main/java/com/thoughtworks/aceleradora/service/EstimateConverterService.java
> +        System.out.println(request.getResidueRequest());
print

2020-12-01 17:42 UTC, GabrieRabelo commented on backend/src/main/java/com/thoughtworks/aceleradora/controller/request/ResidueRequest.java
> +    private String residueMensure;
outra coisa, precisa ter residue no nome? tendo em vista que só tem atributos referente ao residuo?

2020-12-01 17:50 UTC, ldiasrs approved these changes
Muito bom galera!!

Mais tarde podemos trabalhar em como testar esses novos campos no fluxo de conversão.

De resto acho que está fluindo bem. 

Lembrando que se forem mudar o nome dos campos isso precisa ser refletido em um novo changelog SQL para mudar o nome do campo no BD também.

Continuem fazendo testes funcionais locais e rodando os testes e build antes de mergear

Parabéns!!

2020-12-01 18:56 UTC, ghidorsi requested changes

2020-12-01 20:21 UTC, GabrieRabelo commented
Cuidado ao implementarem mais funcionalidades quando o MR já têm aprovações, eu mudaria para WIP (Work in progress) no título para que assim os mentores saibam que ainda estão desenvolvendo.

2020-12-03 12:38 UTC, GabrieRabelo commented on backend/src/main/java/com/thoughtworks/aceleradora/controller/request/ResidueRequest.java
> +    private String residueMensure;
ok, será deixado como melhoria.

2020-12-03 12:40 UTC, GabrieRabelo approved these changes

2020-12-03 12:54 UTC, ghidorsi approved these changes

2020-12-03 14:41 UTC, merged